/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is generated by `next dev` / `next build`. Do not edit.
// Checked in here so the scaffold type-checks straight out of the repo.
